spring:
  application:
    name: frustration-free-k8s
---
spring:
  config:
    activate:
      on-cloud-platform: none
    import: "optional:configserver:"
---
spring:
  config:
    activate.on-cloud-platform: kubernetes
    import: "configserver:http://spring-cloud-kubernetes-configserver:8888"
